apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Optioneel: deploy in een eigen namespace
# namespace: livestream

resources:
  - stream/
  - viewer/

# Voorbeeld van environment-specifieke overrides:
# - patches:
#     - target: { kind: ConfigMap, name: stream-config }
#       patch: |
#         - op: replace
#           path: /data/YOUTUBE_URL
#           value: "https://www.youtube.com/watch?v=abcdef"
#         - op: replace
#           path: /data/VIDEO_BITRATE
#           value: "20000k"
